baseURL: "https://openprivacytech.org"
languageCode: en-us
title: Open Privacy Tech
theme: PaperMod

params:
  homeInfoParams:
    Title: "Hello Stranger"
    Content: Welcome to my blog. Here you'll find a lot of cool information about a lot of cool stuff.
  socialIcons:
    - name: facebook
      url: "https://facebook.com/"
    - name: twitter
      url: "https://twitter.com/"
    - name: github
      url: "https://github.com/"

  cover:
    linkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
    - identifier: resources
      name: Resources
      url: /resources/
      weight: 40
